channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=23.1.2
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - typing-extensions==4.6.3
name: mlflow-env
